

import SubPageLayout from "@/components/sub-page-layout";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <SubPageLayout>
        <Card>
          <CardContent>
            {children}
          </CardContent>
        </Card>
      </SubPageLayout>
    </>
  )
}


