

import SubPageLayout from "@/components/sub-page-layout";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <SubPageLayout>
        <div className="flex justify-center items-center h-full min-h-screen">
          <Card className="w-full max-w-4xl h-full flex flex-col rounded-lg">
            <CardContent className=" flex flex-col p-6 h-full overflow-auto">
              {children}
            </CardContent>
          </Card>
        </div>
      </SubPageLayout>
    </>
  )
}


